In [1]:
import numpy as np
import cv2
import matplotlib.pyplot as plt
# multiple cascades: https://github.com/Itseez/opencv/tree/master/data/haarcascades
import tensorflow as tf
#https://github.com/Itseez/opencv/blob/master/data/haarcascades/haarcascade_frontalface_default.xml
path = "D:\\DriverStateAnalysis\\DriverDrowsinessDetection\\dependencies\\"
face_cascade = cv2.CascadeClassifier(path+'haarcascade_frontalface_default.xml')
#https://github.com/Itseez/opencvblob/master/data/haarcascades/haarcascade_eye.xml
eye_cascade = cv2.CascadeClassifier(path+'haarcascade_eye.xml')

model  =  tf.keras.models.load_model("D:\\DriverStateAnalysis\\DriverDrowsinessDetection\\blinkDetectionCode\\CEWLight.h5")




In [8]:
import time


cap = cv2.VideoCapture(0)

while 1:
    #start= time.time()
    ret, img = cap.read()
    if not ret:
        print("Image reading Failed")
        continue
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    #plt.imshow(gray)
    faces = face_cascade.detectMultiScale(gray, scaleFactor = 1.6, minNeighbors = 7, minSize = (30,30))
    #end = time.time()
    
    print(faces)
    fps = 0
    for (x,y,w,h) in faces:
        cv2.rectangle(img,(x,y),(x+w,y+h),(255,0,0),2)
        roi_gray = gray[y:y+h, x:x+w]
        roi_color = img[y:y+h, x:x+w]
        eyes = eye_cascade.detectMultiScale(roi_gray)
        for (ex,ey,ew,eh) in eyes:
            cv2.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(0,255,0),2)
            image = img[ey:ey+eh,ex:ex+ew]
            image = cv2.resize(image,(75,75))
            image = cv2.resize(image,(75,75))
            image = cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
            image = cv2.cvtColor(image,cv2.COLOR_GRAY2BGR)
            image = image/255.0
            image = [image]
            image = np.array(image)
            #print(image.shape)
            start = time.time()
            pred = model.predict(image)
            end= time.time()
            fps = 1/(end-start)
        
    print("Predicted : ",pred[0][0])

    #fps = 1/(end-start+0.00001)
    print("FPS : ", fps)
    cv2.putText(img,"FPS : "+str(fps),(100,100),cv2.FONT_HERSHEY_COMPLEX,1,(255,0,0),1)

    cv2.imshow('img',img)
    k = cv2.waitKey(30) & 0xff
    if k == 27:
        break

cap.release()
cv2.destroyAllWindows()

[[186 161 252 252]]
1/1 [==============================] - 0s 63ms/step
Predicted :  0.99960524
FPS :  5.709145949713066
[[191 158 252 252]]
1/1 [==============================] - 0s 57ms/step
Predicted :  0.9588168
FPS :  6.857202647205002
[[206 163 252 252]]
1/1 [==============================] - 0s 71ms/step
Predicted :  0.99995375
FPS :  6.651902648832275
[[216 161 252 252]]
1/1 [==============================] - 0s 66ms/step
Predicted :  0.99999857
FPS :  4.997824185618653
[[202 164 252 252]]
1/1 [==============================] - 0s 97ms/step
Predicted :  0.9999937
FPS :  4.491117461942305
[[203 161 252 252]]
1/1 [==============================] - 0s 118ms/step
Predicted :  0.9999883
FPS :  3.859507189352434
[[205 160 252 252]]
1/1 [==============================] - 0s 74ms/step
Predicted :  0.9831647
FPS :  5.18298413953747
[[204 162 252 252]]
1/1 [==============================] - 0s 75ms/step
Predicted :  0.9936162
FPS :  5.917747299182947
[[201 160 252 252]]
1/1 [============